index:
    path: /
    controller: App\Controller\HomeController::index

login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

register:
    path: /register
    controller: App\Controller\SecurityController::show_register_form
    methods: GET|POST
register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: POST