index:
    path: /
    controller: App\Controller\HomeController::index
app_login:
    path:       /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
app_logout:
    path: /logout
    methods: GET
registerForm:
    path: /register
    controller: App\Controller\SecurityController::showRegisterForm
    methods: GET

register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: POST